language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: N/mQUnV8GFwE5TQOc3LxS4zwMWzeacsL6HkTzx5vLFKNndStTCnN60yo4Blu5PyoPiuALJ7sUUXrZug3xZk57Kh/uIWpB6Ug7uJdgej7aT42Y6LG84UIEpmrL6aoG+8MQBO63wv06QRN3XpooKxteHt9ufmpdOgYFqsj+Z71jxF736kyZuczPJZhLI9AHzfoIiSAeQahiAbIC0UgYBUogRRDGTUuDjxj7O9/cXZcmLQmcWlOAdqqLzMbHmt2s9QlyizMV/3zFKBwFgOhqLwQb3Uexh+kELLWPLon/h25chFq/X1GgMvVx6cnjx7SfNOY/PzHgV7wLX/krKP25Sh/s8t9JxEM0f39bF8TxrLVN47I5nqdkgBA0tsk0h/OGOu3wqmEQMyQr5d0MBXnoUz+dRhNAvwDUL38gegfcpHwW/lyUZ6fhJ8iDWjoICwgIP4AgjZ1hHR47b18zzKNotltqR6joxSqeOPpNedzZTpYLvQMO938YvuVNBqgTYmJPFKgRsiJPffh+pWYPezeJOqgFiMtQ+uJpVQszhkJXLIaDoiYk9eduUlRawkpRH68bND+jt8+U7g/gasMtpei3slbfszEwDZDDmTOtOiMYjkwT/cW0ZWPZdH6UVyIp0HHnWducCgcQqCFCPst8xGx/L1Yx4IfAiP5We8qYEEcSib4sLg=
  app: softeng-webapp-ross
  on:
    repo: rossxhunter/BasicWebApp
