language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: GqMDxoktXPRr4tvLqhknZVVtgGf2VeUxKCVnR2w5i90YV8m5HMuehxhW0Ng+EIhAjBmUFu6WIUwsUB+MlmY4F4Cer8Z16z5BogoqhdR/5xuT2pKxCR5EbJm51W0BhmSSXBm/aduYwC3zWawo8qFTqczV6bvHOkeLy8UNbiKyNTAEqr/2iqZ+bNH37pM9EkEhF2s3PJsZcTy2Edc5rPdV2vHp/bEbuNmIAO6skBLTEgGiO0+mOSs09Za1mtnjyfGuyUKj00Ao9XUsjRIW/U9DtIHK6HlG27iUXIv/Kb6qcJ5mSV8JODDr5RRg7nbZxzVJ2OK9/jHkPYi2FY1BYjh1yX03TH6gyFkXWYz7YeT2Z1KhotdR3c7XyzN1G1HyuaPmydB4hlRZdEkQpOTVjmz9TM0VSzqp0VmiUaEsLVMKINBTcxt9p+9UOLOSfEHYTuyMNEnZk+1sDr9aXlyBJFcaf/FRj7nPzhKQdyZ/GfaDN8C+PubNiPDQ5ptMnZf8k6LHvfeqOhaa4Ly6D5QsHc8UDyGBsdHU457bzldSgvfufe37NQDTUMTcUR04UZbDdfbZv44YrsxOUPvxpvOWYg0i6frXlm17QuDPIJs2Wh2XBsvGcBvFZ4W4bV0TRpGEv32W5Dm7wEQ6+mxkHSlqlyX0EFCRVXPlZxf/U938aPAuYGU=
