language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: Y0EaX8gx6noaxM1yYgsaK/EOkkh2veM826hd/a+NC8b34041lKDVpu/wsTKhDoclzzJPbdZKDRIdtSKdGIEhrKEBKOlGtl9GLooGtKxMXU/X47GP2mTpF6FVLDEOCeQOuBgBZg/504fOnLXDfQJCLKG1YmnhR09o1P1JqV3iaoMUW9k+XtdGOpAVQASl3cfK5hGm6stp7H9QNERTXkSzDRICmzWAoTf86+Dc6S8GvjjTc3ujDrjM+Np7AbYCKUDpIo2MeMvv/NNmKa9VZlw2YlvqpZu4nnkZOaerqq7KibKieoIpLrYi7pWV3R2DUQdfF760xN0wLmq1JfuXR3J/1hmR1OCaPp8lrFIse8w97/tuJFYkIplNhkr9pS411pSYbQu4U/XQ5dXdeVHTLpALW0QaauJjSMxojTa9F/kpt+hR2cPtmZzvAiIqPzepBoTj9krsmJBJiMXeL79InWL9yKMxfPurqPogiFAUo2eZIB9Rg5klV80RxAvHm9jl22T5OWP962I4/AWUaqRhRE7pdWu+Loz55/X2EaLd9HvRs+plIq03iChWQ4v0wpEVjWGZsb5klGCQPFmLRqTPwqJs3ozEbArcDd3yxkBFObZ1iPZ4YnHSZsrYhq4HmS13rjPNr2gqCPCDMbtyNx/2nIMeM41FZwp/KJpeFZY0bWGzfJg=
